"use client";
import "./globals.css";
import "./styles.css";
import Iridescence from "./Iridescence";

// const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<title>souic</title>
			</head>
			<body className="overflow-y-scroll">
				<Iridescence
					color={[1, 1, 1]}
					mouseReact={false}
					amplitude={0.1}
					speed={1.0}
				/>
				{children}
			</body>
		</html>
	);
}
